site_name: FMT-MPC
site_description: Documentation for the Fast Marching Tree planning, control, and simulation stack.
repo_url: https://github.com/CagriCatik/FMT-MPC

nav:
  - Home: index.md
  - Introduction: 01_introduction.md
  - System Architecture: 02_system_architecture.md
  - Planning & Control: 03_planning_and_control.md
  - Simulation & Visualisation: 04_simulation_and_visualization.md
  - Configuration & CLI: 05_configuration_and_cli.md
  - Results: 06_results.md

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  logo: null
  favicon: null

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - autorefs
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/example/rrtstar_mpc_motion_planning
  generator: false
  copyright: "Copyright \u00a9 2024 RRT* MPC Motion Planning"

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - assets/js/math-init.js
