name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        default: false
        description: "Run semantic release without publishing"

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install release tooling
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release build
      - name: Run semantic-release
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
          GH_TOKEN: ${{ secrets.MKDOCS_DEPLOY_TOKEN }}
        run: |
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            semantic-release version --noop
          else
            semantic-release publish
          fi
